<a href="https://colab.research.google.com/github/ankitadhara28/Credit-Card-Fraud-Detection/blob/main/credit_Card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Credit Card Fraud Detection

## Introduction
Credit card fraud is a significant problem for financial institutions and consumers alike. This project aims to build a machine learning model to detect fraudulent credit card transactions using a given dataset.

## Dataset
The dataset used is `creditcard_2023.csv`, which contains anonymized transaction data. Key characteristics of the dataset include:
-   **Highly Imbalanced**: As observed, the dataset has a very skewed distribution between legitimate (Class 0) and fraudulent (Class 1) transactions. There are 18309 legitimate transactions and only 81 fraudulent transactions.
-   **Features**: The dataset contains 30 features (V1-V28, Amount, and id), with 'Class' being the target variable indicating whether a transaction is fraudulent (1) or legitimate (0).

## Methodology
The following steps were performed in the notebook:

1.  **Data Loading and Initial Exploration**:
    *   Loaded the `creditcard_2023.csv` into a pandas DataFrame.
    *   Displayed the first and last 5 rows to get a glimpse of the data.
    *   Used `credit_card_data.info()` to check data types and non-null counts.
    *   Checked for missing values using `credit_card_data.isnull().sum()`.
    *   Analyzed the distribution of the 'Class' variable using `value_counts()`.

2.  **Handling Imbalanced Data**:
    *   Separated legitimate and fraudulent transactions into two DataFrames (`legit` and `fraud`).
    *   Created a sample of legitimate transactions (`legit_sample`) with the same number of observations as fraudulent transactions (81 samples).
    *   Concatenated `legit_sample` and `fraud` to create a new, balanced dataset (`new_dataset`).

3.  **Data Splitting**:
    *   Separated features (`x`) from the target variable (`y`).
    *   Split the `new_dataset` into training and testing sets (`x_train`, `x_test`, `y_train`, `y_test`) using `train_test_split` with a `test_size` of 0.2, `stratify=y` to maintain the class distribution, and `random_state=2` for reproducibility.

4.  **Model Training**:
    *   Initialized a `LogisticRegression` model.
    *   Trained the model using the `x_train` and `y_train` datasets.

5.  **Model Evaluation**:
    *   Predicted on the training data and calculated the `accuracy_score`.
    *   Predicted on the test data and calculated the `accuracy_score`.

## Results

The Logistic Regression model achieved the following accuracy scores:
-   **Accuracy on training data**: 0.9767
-   **Accuracy on test data**: 0.9394

## Conclusion
The model shows good performance with high accuracy on both training and test datasets. The balancing of the dataset was crucial in enabling the model to learn from both classes effectively. Further improvements could involve exploring other classification algorithms, hyperparameter tuning, or more advanced feature engineering techniques.

In [7]:
# importing all the dependencies
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [8]:
# loading the dataset to the pandas DataFrame
credit_card_data = pd.read_csv("/content/creditcard_2023.csv")

In [9]:
# displaying first 5 rows of the dataset
credit_card_data.head()

   id        V1        V2        V3  ...       V27       V28    Amount  Class
0   0 -0.260648 -0.469648  2.496266  ... -0.081230 -0.151045  17982.10    0.0
1   1  0.985100 -0.356045  0.558056  ... -0.248052 -0.064512   6531.37    0.0
2   2 -0.260272 -0.949385  1.728538  ... -0.300258 -0.244718   2513.54    0.0
3   3 -0.152152 -0.508959  1.746840  ... -0.165316  0.048424   5384.44    0.0
4   4 -0.206820 -0.165280  1.527053  ...  0.023712  0.419117  14278.97    0.0

[5 rows x 31 columns]

In [10]:
# displaying last 5 rows
credit_card_data.tail()

          id        V1        V2        V3  ...       V27       V28    Amount  Class
18386  18386  0.857988 -0.288022  0.495975  ... -0.258917 -0.103803  20269.23    0.0
18387  18387  0.950437 -0.951018  0.599227  ... -0.113027 -0.018291  19042.19    0.0
18388  18388 -0.379280  0.204033  0.405852  ... -0.355992  0.069531   6975.19    0.0
18389  18389  0.001842 -0.374023  0.710190  ... -0.422965 -0.418794  22310.04    0.0
18390  18390  0.026208 -0.410460  2.016013  ...       NaN       NaN       NaN    NaN

[5 rows x 31 columns]

In [11]:
# dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18391 entries, 0 to 18390
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      18391 non-null  int64
 1   V1      18391 non-null  float64
 2   V2      18391 non-null  float64
 3   V3      18391 non-null  float64
 4   V4      18391 non-null  float64
 5   V5      18391 non-null  float64
 6   V6      18391 non-null  float64
 7   V7      18391 non-null  float64
 8   V8      18391 non-null  float64
 9   V9      18391 non-null  float64
 10  V10     18391 non-null  float64
 11  V11     18391 non-null  float64
 12  V12     18391 non-null  float64
 13  V13     18391 non-null  float64
 14  V14     18391 non-null  float64
 15  V15     18391 non-null  float64
 16  V16     18391 non-null  float64
 17  V17     18391 non-null  float64
 18  V18     18391 non-null  float64
 19  V19     18391 non-null  float64
 20  V20     18391 non-null  float64
 21  V21     18390 non-null  float64
 22  V22     18390 non-null  float64
 23  V23     18390 non-null  float64
 24  V24     18390 non-null  float64
 25  V25     18390 non-null  float64
 26  V26     18390 non-null  float64
 27  V27     18390 non-null  float64
 28  V28     18390 non-null  float64
 29  Amount  18390 non-null  float64
 30  Class   18390 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 4.3 MB

In [12]:
# chceking no of misssing values in each column
credit_card_data.isnull().sum()

id        0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [14]:
# distribution of legit transaction and fradulent transaction
credit_card_data['Class'].value_counts()

Class
0.0    18309
1.0       81
Name: count, dtype: int64

The dataset is highly unbalanced having unbalanced values for class 0 and class 1.

0 --> Normal Transaction

1 --> Fradulent Transaction

In [15]:
#seperating the data for analysis

legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]
print(legit.shape)
print(fraud.shape)

(18309, 31)
(81, 31)

In [16]:
# statistical measures of the data
legit.Amount.describe()

count    18309.000000
mean     11904.577719
std       6923.745906
min         50.410000
25%       5905.730000
50%      11776.970000
75%      17909.570000
max      24039.880000
Name: Amount, dtype: float64

In [17]:
fraud.Amount.describe()

count       81.000000
mean     11626.547284
std       6636.709826
min        925.610000
25%       5744.140000
50%      11281.610000
75%      17207.310000
max      23690.300000
Name: Amount, dtype: float64

In [18]:
# compare the values for both transaction
credit_card_data.groupby('Class').mean()

                 id        V1        V2  ...       V27       V28        Amount
Class                                    ...
0.0     9188.062264  0.321989 -0.403720  ... -0.203603 -0.084535  11904.577719
1.0    10649.666667 -0.951755  1.250584  ...  1.218448  0.108108  11626.547284

[2 rows x 30 columns]

Build a Sample Dataset containing similiar distribution of normal transaction and Fradulent Transactions.

In [19]:
legit_sample = legit.sample(n=81)

In [21]:
# concatenating two data frame
new_dataset = pd.concat([legit_sample , fraud],axis = 0)

In [22]:
new_dataset.head()

          id        V1        V2        V3  ...       V27       V28    Amount  Class
6998    6998  1.147544 -0.598617  0.573447  ... -0.287760 -0.099095   3376.37    0.0
10160  10160  0.853807 -0.360462  1.702063  ... -0.206936 -0.059220   5251.12    0.0
5246    5246  1.014343 -0.203245  0.399527  ... -0.249041 -0.008619  18884.68    0.0
5075    5075  0.923416 -0.517144  1.258002  ... -0.240285 -0.092580  19754.06    0.0
7617    7617 -1.100626 -7.295642 -0.372341  ... -0.948277  1.568333   7606.44    0.0

[5 rows x 31 columns]

In [23]:
new_dataset.tail()

          id        V1        V2        V3  ...       V27       V28    Amount  Class
17317  17317 -2.521749  3.153763 -2.417978  ...  1.624072  0.835026    925.61    1.0
17366  17366 -2.551425  3.207646 -2.443510  ...  1.586523  0.816186   8102.86    1.0
17407  17407 -2.580623  3.261359 -2.468736  ...  1.549170  0.797321  19918.66    1.0
17453  17453 -2.609364  3.314906 -2.493666  ...  1.512010  0.778434   1111.14    1.0
17480  17480 -2.637662  3.368287 -2.518308  ...  1.475041  0.759524  19813.32    1.0

[5 rows x 31 columns]

In [24]:
new_dataset['Class'].value_counts()

Class
0.0    81
1.0    81
Name: count, dtype: int64

In [26]:
new_dataset.groupby('Class').mean()

                 id        V1        V2  ...       V27       V28        Amount
Class                                    ...
0.0     8867.555556  0.289150 -0.464373  ... -0.247416  0.020957  12326.765926
1.0    10649.666667 -0.951755  1.250584  ...  1.218448  0.108108  11626.547284

[2 rows x 30 columns]

Splitting data into features and target

In [27]:
x = new_dataset.drop(columns = 'Class',axis = 1)
y = new_dataset['Class']
print(x)
print(y)

          id        V1        V2  ...       V27       V28    Amount
6998    6998  1.147544 -0.598617  ... -0.287760 -0.099095   3376.37
10160  10160  0.853807 -0.360462  ... -0.206936 -0.059220   5251.12
5246    5246  1.014343 -0.203245  ... -0.249041 -0.008619  18884.68
5075    5075  0.923416 -0.517144  ... -0.240285 -0.092580  19754.06
7617    7617 -1.100626 -7.295642  ... -0.948277  1.568333   7606.44
...      ...       ...       ...  ...       ...       ...       ...
17317  17317 -2.521749  3.153763  ...  1.624072  0.835026    925.61
17366  17366 -2.551425  3.207646  ...  1.586523  0.816186   8102.86
17407  17407 -2.580623  3.261359  ...  1.549170  0.797321  19918.66
17453  17453 -2.609364  3.314906  ...  1.512010  0.778434   1111.14
17480  17480 -2.637662  3.368287  ...  1.475041  0.759524  19813.32

[162 rows x 30 columns]
6998     0.0
10160    0.0
5246     0.0
5075     0.0
7617     0.0
        ...
17317    1.0
17366    1.0
17407    1.0
17453    1.0
17480    1.0
Name: Class, Length: 162, dtype: float64

Split data into train and test data

In [28]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, stratify = y, random_state=2)

In [30]:
print(x.shape , x_train.shape , x_test.shape)

(162, 30) (129, 30) (33, 30)

Using Logistic Regression model for binary data

In [32]:
model = LogisticRegression()

In [33]:
# training the logistic regression model with training data
model.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation based on accuracy score

In [35]:
# accuracy score on training data
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction,y_train)
print('Accuracy on training data : ',training_data_accuracy)

Accuracy on training data :  0.9767441860465116

In [36]:
# accuracy on test data
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)
print('Accuracy on test data:', test_data_accuracy)

Accuracy on test data: 0.9393939393939394

# Credit Card Fraud Detection

![Python Version](https://img.shields.io/badge/Python-3.x-blue.svg)
![Scikit-learn Version](https://img.shields.io/badge/Scikit--learn-0.24%2B-orange.svg)

## Table of Contents
- [Introduction](#introduction)
- [Dataset](#dataset)
- [Methodology](#methodology)
- [Results](#results)
- [Future Improvements](#future-improvements)
- [Installation](#installation)
- [Usage](#usage)
- [Contributing](#contributing)
- [License](#license)

## Introduction
This project focuses on building a machine learning model to detect fraudulent credit card transactions. Credit card fraud is a significant challenge for financial institutions and consumers, leading to substantial financial losses and erosion of trust. By leveraging machine learning, we aim to accurately identify suspicious transactions, thereby minimizing fraudulent activities.

## Dataset
The dataset used for this project is `creditcard_2023.csv`, obtained from a publicly available source (e.g., Kaggle). It contains anonymized transaction data with the following key characteristics:

-   **Highly Imbalanced**: The dataset exhibits a severe class imbalance, with a significantly higher number of legitimate transactions (Class 0) compared to fraudulent ones (Class 1). Specifically, there are 18309 legitimate transactions and only 81 fraudulent transactions.
-   **Features**: The dataset comprises 30 features, primarily anonymized principal components (`V1` through `V28`), `Amount`, and `id`. The target variable, `Class`, indicates whether a transaction is legitimate (0) or fraudulent (1).

## Methodology
The fraud detection model was developed following these key steps:

1.  **Data Loading and Initial Exploration**:
    *   Loaded the `creditcard_2023.csv` file into a pandas DataFrame.
    *   Performed initial checks on the data, including viewing the first/last rows, inspecting data types (`.info()`), and identifying missing values (`.isnull().sum()`).
    *   Analyzed the distribution of the `Class` variable to understand the extent of class imbalance.

2.  **Handling Imbalanced Data**:
    *   To address the severe class imbalance, a balanced dataset was created. Legitimate transactions (Class 0) and fraudulent transactions (Class 1) were separated.
    *   A sample of legitimate transactions (`legit_sample`) was randomly selected to match the number of fraudulent transactions (81 samples).
    *   These two subsets (`legit_sample` and `fraud`) were then concatenated to form a new, balanced dataset (`new_dataset`).

3.  **Data Splitting**:
    *   The balanced dataset was split into features (`x`, dropping the 'Class' column) and the target variable (`y`, the 'Class' column).
    *   The data was further divided into training and testing sets (`x_train`, `x_test`, `y_train`, `y_test`) using `train_test_split`. A `test_size` of 0.2 (20% for testing) was used, with `stratify=y` to ensure that the class distribution is preserved in both training and testing sets, and `random_state=2` for reproducibility.

4.  **Model Training**:
    *   A Logistic Regression model (`LogisticRegression()`) was initialized.
    *   The model was trained using the `x_train` and `y_train` datasets.

5.  **Model Evaluation**:
    *   The trained model's performance was evaluated using `accuracy_score` on both the training and testing datasets.

## Results

The Logistic Regression model achieved the following accuracy scores:

-   **Accuracy on training data**: `0.9767` (approximately 97.67%)
-   **Accuracy on test data**: `0.9394` (approximately 93.94%)

These results indicate that the model performs well on both seen and unseen data, demonstrating its ability to generalize. The balancing technique applied was effective in allowing the model to learn from the minority class.

## Future Improvements

To further enhance the model's performance and robustness, consider the following:

-   **Exploring other algorithms**: Evaluate other classification algorithms such as Random Forest, Gradient Boosting, or Support Vector Machines.
-   **Hyperparameter Tuning**: Optimize the hyperparameters of the chosen model using techniques like GridSearchCV or RandomizedSearchCV.
-   **Advanced Resampling Techniques**: Investigate more sophisticated resampling methods (e.g., SMOTE, ADASYN) for handling imbalanced datasets.
-   **Feature Engineering**: Create new features from existing ones that might provide more predictive power.
-   **Cross-Validation**: Implement k-fold cross-validation for a more robust evaluation of the model's performance.

## Installation

To run this notebook, you will need the following Python libraries. You can install them using pip:

```bash
pip install pandas numpy scikit-learn
```

## Usage

1.  Clone this repository:
    ```bash
    git clone https://github.com/yourusername/credit-card-fraud-detection.git
    cd credit-card-fraud-detection
    ```
2.  Place the `creditcard_2023.csv` dataset in the same directory as the notebook.
3.  Open the `Credit Card Fraud Detection.ipynb` notebook in Google Colab or Jupyter Notebook.
4.  Run all cells to replicate the analysis and model training.

## Contributing

Contributions are welcome! If you have suggestions for improvements or new features, please open an issue or submit a pull request.

## License

This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details.